version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: spy-cats-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spy_cats_agency
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d spy_cats_agency"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
